### ISSUE TITLE
What's the use-case for "12-12-12-12"?

### ISSUE THREAD

**Issue by brianosman** [WICG/canvas-color-space#11]
Reading through the most recent version, and spotted the "12-12-12-12" pixel format. That doesn't seem like an efficient format (for CPU or GPU), and it's not clear how it maps to JS types, either. What's the motivation for its inclusion, and the expected usage scenario?

Additionally, if the answer is "Rec.2020 prescribes 12 bits/channel for precision", then we're stepping into the HDR minefield (which is actually already happening). Rec.2020's transfer function assumes a specific output luminance based on the encoding, so to get "display white" rather than "blinding white", anyone that's rendering to 12-bit (assuming that data somehow gets piped directly to a Rec.2020 display) is going to want to normalize their output in the bottom half of the usable range.

**Comment by jdashg** [comment]
Generally this is exposed to graphics APIs as unorm16 with zeros/padding, but we don't have 12bpc in the current proposal anymore anyway.
