### ISSUE TITLE
CSS for HDR values?

### ISSUE THREAD

**Issue by greggman** [WICG/canvas-color-space#24]
The 2D canvas API gets colors from CSS colors. Many CSS colors are defined as 8 bit colors, example

     rgb(255, 0, 255)

I'm just guessing the CSS spec doesn't handle `rgb(512,0,1024)` if you want 2,0,4 float values written into a the canvas.  What happens here?

**Comment by svgeesus** [comment]
Many CSS colors are defined as 8 bit per component, yes. For sRGB:

[`#FF00FF`](https://drafts.csswg.org/css-color-4/#hex-notation)
[`rgb(255 0 255)`](https://drafts.csswg.org/css-color-4/#rgb-functions)

other sRGB colors take a float (for backward compat with CSS1, this uses a percentage):

[`rgb(100%, 0%, 100%)`](https://drafts.csswg.org/css-color-4/#rgb-functions)

(this example happens to use integer percent values, but it need not)

`rgb(87.265% 12.35867573% 45.454545%)`

More recently added color functions tend to use a normalized 0.0 .. 1.0 range, for example

[`color(display-p3 0.73452 0.2345 0.89321)`](https://drafts.csswg.org/css-color-4/#valdef-color-display-p3)

> I'm just guessing the CSS spec doesn't handle rgb(512,0,1024) if you want 2,0,4 float values written into a the canvas. What happens here?

No need to guess, the spec is explicit:

> [Values outside these ranges are not invalid, but are clamped to the ranges defined here at computed-value time.](https://drafts.csswg.org/css-color-4/#rgb-functions)

> [The display-p3 colorspace accepts three numeric parameters, representing the red, green, and blue channels of the color, with each having a valid range of [0, 1]](https://drafts.csswg.org/css-color-4/#color-function)

(Notice that in the `rgb(512,0,1024)` example, GitHub displays a magenta swatch produced by simple per-component clipping, equivalent to `rgb(255, 0, 255)`)

There are [open issues on css color 4](https://github.com/w3c/csswg-drafts/issues?utf8=%E2%9C%93&q=is%3Aissue+HDR+css-color) about adding HDR support. [Extending rgb() for HDR](https://github.com/w3c/csswg-drafts/issues/3249) is one option. One problem is relative vs. absolute luminance. In theory, [sRGB uses 80cd/m^2 for graphics white](https://github.com/w3c/csswg-drafts/issues/3435); in practice it doesn't, but scales to whatever monitor brightness has been set. For HDR content, Hybrid Log Gamma (HLG) uses relative luminance, while Perceptual Quantization (PQ) sets the peak specular white at 10,000cd/m^2.

**Comment by Crissov** [comment]
> More recently added color functions tend to use a normalized 0.0 .. 1.0 range, 

https://github.com/w3c/csswg-drafts/issues/3450
https://github.com/w3c/csswg-drafts/issues/4494

**Comment by jdashg** [comment]
I believe CSS color 4 handles this now.
