### ISSUE TITLE
Is this still active?

### ISSUE THREAD

**Issue by marcoscaceres** [WICG/canvas-color-space#29]
Hi Folks, the @wicg/Chairs are wondering if this repo is still active? Let us know if we can archive this.

**Comment by marcoscaceres** [comment]
Related https://github.com/WICG/canvas-color-space/issues/26

**Comment by fserb** [comment]
Yes. @ccameron-chromium is currently working on this. We've been actively looking for someone that can review PRs for this.

**Comment by marcoscaceres** [comment]
This is the kind of stuff @grorg likes :) Maybe he can comment.

**Comment by kenrussell** [comment]
https://github.com/WICG/canvas-color-space/pull/28 just landed moving this proposal forward again. Let's close this issue.
